//
//  TFYShaperLayerChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/11.
//

#import "TFYShaperLayerChainModel.h"

#define TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYShaperLayerChainModel *, CAShapeLayer)

@implementation TFYShaperLayerChainModel

TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(path, CGPathRef)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(fillColor, CGColorRef)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(fillRule, CAShapeLayerFillRule)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeColor, CGColorRef)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeStart, CGFloat)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeEnd, CGFloat)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineWidth, CGFloat)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(miterLimit, CGFloat)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineCap, CAShapeLayerLineCap)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineJoin, CAShapeLayerLineJoin)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineDashPhase, CGFloat)
TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineDashPattern, NSArray<NSNumber *> *)
@end
TFY_CATEGORY_LAYER_IMPLEMENTATION(CAShapeLayer, TFYShaperLayerChainModel)
#undef TFY_CATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION

