//
//  TFYTextLayerChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/11.
//

#import "TFYTextLayerChainModel.h"

#define TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYTextLayerChainModel *, CATextLayer)

@implementation TFYTextLayerChainModel

TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(string, id)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(font, CFTypeRef)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(fontSize, CGFloat)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(foregroundColor, CGColorRef)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(wrapped, BOOL)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(truncationMode, CATextLayerTruncationMode)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(alignmentMode, CATextLayerAlignmentMode)
TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(allowsFontSubpixelQuantization, BOOL)

@end
TFY_CATEGORY_LAYER_IMPLEMENTATION(CATextLayer, TFYTextLayerChainModel)
#undef TFY_CATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION

