//
//  TFYColorWellChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYColorWellChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYColorWellChainModel *,NSColorWell)

@implementation TFYColorWellChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(pulldownAction, SEL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(color, NSColor*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(colorWellStyle, NSColorWellStyle)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(image, NSImage*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(pulldownTarget, id)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSColorWell, TFYColorWellChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION
