//
//  TFYComboButtonChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYComboButtonChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYComboButtonChainModel *,NSComboButton)

@implementation TFYComboButtonChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(title, NSString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(image, NSImage*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(imageScaling, NSImageScaling)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(menu, NSMenu*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(style, NSComboButtonStyle)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION_MACOS13(NSComboButton, TFYComboButtonChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION

