//
//  TFYImageViewChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYImageViewChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYImageViewChainModel *,NSImageView)

@implementation TFYImageViewChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(image, NSImage*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(editable, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(imageAlignment, NSImageAlignment)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(imageScaling, NSImageScaling)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(imageFrameStyle, NSImageFrameStyle)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(symbolConfiguration, NSImageSymbolConfiguration*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(contentTintColor, NSColor*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(animates, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(allowsCutCopyPaste, BOOL)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSImageView, TFYImageViewChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION
