//
//  TFYPathControlChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYPathControlChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYPathControlChainModel *,NSPathControl)

@implementation TFYPathControlChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(editable, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(allowedTypes, NSArray<NSString *> *)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(placeholderString, NSString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(placeholderAttributedString, NSAttributedString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(URL, NSURL*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(doubleAction, SEL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(pathStyle, NSPathStyle)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(pathItems, NSArray<NSPathControlItem *> *)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(backgroundColor, NSColor*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(delegate, id <NSPathControlDelegate>)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(menu, NSMenu*)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSPathControl, TFYPathControlChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION
