//
//  TFYRuleEditorChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYRuleEditorChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYRuleEditorChainModel *,NSRuleEditor)

@implementation TFYRuleEditorChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(delegate, id<NSRuleEditorDelegate>)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(formattingStringsFilename, NSString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(formattingDictionary, NSDictionary *)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(nestingMode, NSRuleEditorNestingMode)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(rowHeight, CGFloat)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(editable, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(canRemoveAllRows, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(rowClass, Class)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(rowTypeKeyPath, NSString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(subrowsKeyPath, NSString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(criteriaKeyPath, NSString*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(displayValuesKeyPath, NSString*)


@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSRuleEditor, TFYRuleEditorChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION
