//
//  TFYRulerViewChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/12.
//

#import "TFYRulerViewChainModel.h"

#define TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYRulerViewChainModel *,NSRulerView)

@implementation TFYRulerViewChainModel

TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(scrollView, NSScrollView*)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(orientation, NSRulerOrientation)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(ruleThickness, CGFloat)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(reservedThicknessForMarkers, CGFloat)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(reservedThicknessForAccessoryView, CGFloat)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(measurementUnits, NSRulerViewUnitName)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(originOffset, CGFloat)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(clientView, NSView*)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(markers, NSArray<NSRulerMarker *> *)
TFY_CATEGORY_CHAIN_RULER_IMPLEMENTATION(accessoryView, NSView*)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSRulerView, TFYRulerViewChainModel)
#undef TFY_CATEGORY_CHAIN_DATEPICKER_IMPLEMENTATION

