//
//  TFYSliderChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYSliderChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYSliderChainModel *,NSSlider)

@implementation TFYSliderChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(vertical, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(allowsTickMarkValuesOnly, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(sliderType, NSSliderType)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(minValue, double)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(maxValue, double)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(altIncrementValue, double)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(trackFillColor, NSColor*)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(numberOfTickMarks, NSInteger)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(tickMarkPosition, NSTickMarkPosition)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSSlider, TFYSliderChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION


