//
//  TFYStepperChainModel.m
//  TFYMacOSAppKit_OC
//
//  Created by 田风有 on 2023/2/13.
//

#import "TFYStepperChainModel.h"

#define TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(TFYMethod,TFYParaType) TFY_CATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(TFYMethod,TFYParaType, TFYStepperChainModel *,NSStepper)


@implementation TFYStepperChainModel

TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(minValue, double)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(maxValue, double)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(increment, double)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(valueWraps, BOOL)
TFY_CATEGORY_CHAIN_UNIFICATION_IMPLEMENTATION(autorepeat, BOOL)

@end
TFY_CATEGORY_VIEW_IMPLEMENTATION(NSStepper, TFYStepperChainModel)
#undef TFY_CATEGORY_CHAIN_BUTTON_IMPLEMENTATION
